apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart
  namespace: argocd
spec:
  destination:
    namespace: 'default'
    server: https://kubernetes.default.svc
  sources:
  - repoURL: https://github.com/Shaked/appset-test.git
    path: 'chart'
    targetRevision: 1a01847
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
      - $values/values/xyz.yaml
  - repoURL: https://github.com/Shaked/appset-test.git
    targetRevision: HEAD
    ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
